<?php declare(strict_types = 1);

require __DIR__ . '/vendor/autoload.php';

$loripsum = new Bmonteirog\Loripsum\Wrapper;


echo $loripsum->render(); // Render 4 paragraphs in default Mode

/*
Response:

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid dubitas igitur mutare principia naturae? Duo enim genera quae erant, fecit tria. Nihilo beatiorem esse Metellum quam Regulum. Duo Reges: constructio interrete. Illa tamen simplicia, vestra versuta. Varietates autem iniurasque fortunae facile veteres philosophorum praeceptis instituta vita superabat. Si verbum sequimur, primum longius verbum praepositum quam bonum. Sed fac ista esse non inportuna; </p>

<p>An potest, inquit ille, quicquam esse suavius quam nihil dolere? Et quidem, Cato, hanc totam copiam iam Lucullo nostro notam esse oportebit; Sed tamen enitar et, si minus multa mihi occurrent, non fugiam ista popularia. Nos cum te, M. Te enim iudicem aequum puto, modo quae dicat ille bene noris. </p>

<p>Omnes enim iucundum motum, quo sensus hilaretur. Nihil opus est exemplis hoc facere longius. Quid ei reliquisti, nisi te, quoquo modo loqueretur, intellegere, quid diceret? Cur, nisi quod turpis oratio est? </p>

<p>Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Non quam nostram quidem, inquit Pomponius iocans; Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Quamquam te quidem video minime esse deterritum. Huius, Lyco, oratione locuples, rebus ipsis ielunior. Eadem nunc mea adversum te oratio est. Videsne quam sit magna dissensio? Quid censes in Latino fore? </p>
*/

echo $loripsum->length('short')
               ->withLinks()
               ->render(2); // Render 2 short paragraphs with links

/*
Response:

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quid enim possumus hoc agere divinius? <a href='http://loripsum.net/' target='_blank'>Nihil sane.</a> Quid de Pythagora? <a href='http://loripsum.net/' target='_blank'>Comprehensum, quod cognitum non habet?</a> Duo Reges: constructio interrete. Suo genere perveniant ad extremum; </p>

<p>Bonum liberi: misera orbitas. Sed quod proximum fuit non vidit. <a href='http://loripsum.net/' target='_blank'>Que Manilium, ab iisque M.</a> Ecce aliud simile dissimile. <a href='http://loripsum.net/' target='_blank'>Non autem hoc: igitur ne illud quidem.</a> </p>
*/

echo $loripsum->length('short')
              ->isPlaintext()
              ->render(2); // Render 2 short plain text paragraphs

/*
Response:

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Hoc Hieronymus summum bonum esse dixit. Quae cum dixisset, finem ille. Honesta oratio, Socratica, Platonis etiam. Si longus, levis. Nos cum te, M. Duo Reges: constructio interrete.

Hoc simile tandem est? Cyrenaici quidem non recusant;
*/


echo $loripsum->length('verylong')
              ->decorated()
              ->withLinks()
              ->withUnorderedLists()
              ->withNumberedLists()
              ->withDescriptionLists()
              ->withBlockquotes()
              ->withCode()
              ->withHeaders()
              ->isAllCaps()
              ->isPrude()
              ->render(10); // Render 10 verylong paragraphs with All options

/*
Response:

<H1>ATQUI ISTE LOCUS EST, PISO, TIBI ETIAM ATQUE ETIAM CONFIRMANDUS, INQUAM;</H1>

<P>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. <B>COLLATIO IGITUR ISTA TE NIHIL IUVAT.</B> QUI HAEC DIDICERUNT, QUAE ILLE CONTEMNIT, SIC SOLENT: DUO GENERA CUPIDITATUM, NATURALES ET INANES, NATURALIUM DUO, NECESSARIAE ET NON NECESSARIAE. QUAM OB REM TURPE PUTANDUM EST, NON DICO DOLERE-NAM ID QUIDEM EST INTERDUM NECESSE-, SED SAXUM ILLUD LEMNIUM CLAMORE PHILOCTETEO FUNESTARE, QUOD EIULATU, QUESTU, GEMITU, FREMITIBUS RESONANDO MUTUM FLEBILES VOCES REFERT. PRIMUM NON SAEPE, DEINDE QUAE EST ISTA RELAXATIO, CUM ET PRAETERITI DOLORIS MEMORIA RECENS EST ET FUTURI ATQUE INPENDENTIS TORQUET TIMOR? DUO REGES: CONSTRUCTIO INTERRETE. AN NE HOC QUIDEM PERIPATETICIS CONCEDIS, UT DICANT OMNIUM BONORUM VIRORUM, ID EST SAPIENTIUM OMNIBUSQUE VIRTUTIBUS ORNATORUM, VITAM OMNIBUS PARTIBUS PLUS HABERE SEMPER BONI QUAM MALI? AT MISER, SI IN FLAGITIOSA ET VITIOSA VITA AFFLUERET VOLUPTATIBUS. <CODE>QUAERIMUS ENIM FINEM BONORUM.</CODE> <CODE>BEATUS SIBI VIDETUR ESSE MORIENS.</CODE> <B>HUIUS EGO NUNC AUCTORITATEM SEQUENS IDEM FACIAM.</B> <I>QUID AD UTILITATEM TANTAE PECUNIAE?</I> <CODE>CERTE NON POTEST.</CODE> UTRUM ENIM SIT VOLUPTAS IN IIS REBUS, QUAS PRIMAS SECUNDUM NATURAM ESSE DIXIMUS, NECNE SIT AD ID, QUOD AGIMUS, NIHIL INTEREST. SI VERO ID ETIAM EXPLANARE VELLES APERTIUSQUE DICERES NIHIL EUM FECISSE NISI VOLUPTATIS CAUSA, QUO MODO EUM TANDEM LATURUM FUISSE EXISTIMAS? ILLORUM VERO ISTA IPSA QUAM EXILIA DE VIRTUTIS VI! QUAM TANTAM VOLUNT ESSE, UT BEATUM PER SE EFFICERE POSSIT. <I>ILLE INCENDAT?</I> <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>SCRUPULUM, INQUAM, ABEUNTI;</A> FACIT IGITUR LUCIUS NOSTER PRUDENTER, QUI AUDIRE DE SUMMO BONO POTISSIMUM VELIT; EST ENIM ALIQUID IN HIS REBUS PROBABILE, ET QUIDEM ITA, UT EIUS RATIO REDDI POSSIT, ERGO UT ETIAM PROBABILITER ACTI RATIO REDDI POSSIT. VIDEMUSNE UT PUERI NE VERBERIBUS QUIDEM A CONTEMPLANDIS REBUS PERQUIRENDISQUE DETERREANTUR? </P>

<PRE>
SED ID NE COGITARI QUIDEM POTEST QUALE SIT, UT NON REPUGNET
IPSUM SIBI.

HIC, QUI UTRUMQUE PROBAT, AMBOBUS DEBUIT UTI, SICUT FACIT
RE, NEQUE TAMEN DIVIDIT VERBIS.
</PRE>


<H4>EAEDEM RES MANEANT ALIO MODO.</H4>

<P>TOLLITUR BENEFICIUM, TOLLITUR GRATIA, QUAE SUNT VINCLA CONCORDIAE. TUBERONEM DE DOLORE PATIENDO SCRIBERET, QUOD ESSE CAPUT DEBEBAT, SI PROBARI POSSET, NUSQUAM POSUIT, NON ESSE MALUM DOLOREM, SED QUID ESSET ET QUALE, QUANTUMQUE IN EO INESSET ALIENI, DEINDE QUAE RATIO ESSET PERFERENDI; SIN AUTEM EOS NON PROBABAT, QUID ATTINUIT CUM IIS, QUIBUSCUM RE CONCINEBAT, VERBIS DISCREPARE? TANTUM DICO, MAGIS FUISSE VESTRUM AGERE EPICURI DIEM NATALEM, QUAM ILLIUS TESTAMENTO CAVERE UT AGERETUR. NATURA IGITUR CORPUS QUIDEM BOMINIS SIC ET GENUIT ET FORMAVIT, UT ALIA IN PRIMO ORTU PERFICERET, ALIA PROGREDIENTE AETATE FINGERET NEQUE SANE MULTUM ADIUMENTIS EXTERNIS ET ADVENTICIIS UTERETUR. SED SI DUO HONESTA PROPOSITA SINT, ALTERUM CUM VALITUDINE, ALTERUM CUM MORBO, NON ESSE DUBIUM, AD UTRUM EORUM NATURA NOS IPSA DEDUCTURA SIT. <B>AT ENIM HIC ETIAM DOLORE.</B> NEGARINE ULLO MODO POSSIT NUMQUAM QUEMQUAM STABILI ET FIRMO ET MAGNO ANIMO, QUEM FORTEM VIRUM DICIMUS, EFFICI POSSE, NISI CONSTITUTUM SIT NON ESSE MALUM DOLOREM? <MARK>CONFERAM TECUM, QUAM CUIQUE VERSO REM SUBICIAS;</MARK> VERUM UT HAEC NON IN POSTERIS ET IN CONSEQUENTIBUS, SED IN PRIMIS CONTINUO PECCATA SUNT, SIC EA, QUAE PROFICISCUNTUR A VIRTUTE, SUSCEPTIONE PRIMA, NON PERFECTIONE RECTA SUNT IUDICANDA. <I>QUAE SIMILITUDO IN GENERE ETIAM HUMANO APPARET.</I> VOS AUTEM, CATO, QUIA VIRTUS, UT OMNES FATEMUR, ALTISSIMUM LOCUM IN HOMINE ET MAXIME EXCELLENTEM TENET, ET QUOD EOS, QUI SAPIENTES SUNT, ABSOLUTOS ET PERFECTOS PUTAMUS, ACIEM ANIMORUM NOSTRORUM VIRTUTIS SPLENDORE PRAESTRINGITIS. HOC AUTEM LOCO TANTUM EXPLICEMUS HAEC HONESTA, QUAE DICO, PRAETERQUAM QUOD NOSMET IPSOS DILIGAMUS, PRAETEREA SUAPTE NATURA PER SE ESSE EXPETENDA. COMPREHENSUM, QUOD COGNITUM NON HABET? QUIBUS AUTEM IN REBUS TANTA OBSCURATIO NON FIT, FIERI TAMEN POTEST, UT ID IPSUM, QUOD INTEREST, NON SIT MAGNUM. OMNEM VIM LOQUENDI, UT IAM ANTE ARISTOTELES, IN DUAS TRIBUTAM ESSE PARTES, RHETORICAM PALMAE, DIALECTICAM PUGNI SIMILEM ESSE DICEBAT, QUOD LATIUS LOQUERENTUR RHETORES, DIALECTICI AUTEM COMPRESSIUS. PUNGUNT QUASI ACULEIS INTERROGATIUNCULIS ANGUSTIS, QUIBUS ETIAM QUI ASSENTIUNTUR NIHIL COMMUTANTUR ANIMO ET IDEM ABEUNT, QUI VENERANT. <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>NUNC VIDES, QUID FACIAT.</A> PRAETEREA ET APPETENDI ET REFUGIENDI ET OMNINO RERUM GERENDARUM INITIA PROFICISCUNTUR AUT A VOLUPTATE AUT A DOLORE. QUODSI ESSET IN VOLUPTATE SUMMUM BONUM, UT DICITIS, OPTABILE ESSET MAXIMA IN VOLUPTATE NULLO INTERVALLO INTERIECTO DIES NOCTESQUE VERSARI, CUM OMNES SENSUS DULCEDINE OMNI QUASI PERFUSI MOVERENTUR. </P>

<DL>
        <DT><DFN>SEDULO, INQUAM, FACIAM.</DFN></DT>
        <DD>QUOD SI ITA SE HABEAT, NON POSSIT BEATAM PRAESTARE VITAM SAPIENTIA.</DD>
        <DT><DFN>QUARE CONARE, QUAESO.</DFN></DT>
        <DD>QUAE CUM MAGNIFICE PRIMO DICI VIDERENTUR, CONSIDERATA MINUS PROBABANTUR.</DD>
        <DT><DFN>FRATER ET T.</DFN></DT>
        <DD>CUPIT ENIM DíCERE NIHIL POSSE AD BEATAM VITAM DEESSE SAPIENTI.</DD>
        <DT><DFN>VENIT AD EXTREMUM;</DFN></DT>
        <DD>ET CERTAMEN HONESTUM ET DISPUTATIO SPLENDIDA! OMNIS EST ENIM DE VIRTUTIS DIGNITATE CONTENTIO.</DD>
        <DT><DFN>NEGARE NON POSSUM.</DFN></DT>
        <DD>AT HOC IN EO M.</DD>
        <DT><DFN>EFFICIENS DICI POTEST.</DFN></DT>
        <DD>AT QUICUM IOCA SERIA, UT DICITUR, QUICUM ARCANA, QUICUM OCCULTA OMNIA?</DD>
</DL>


<OL>
        <LI>NON ENIM SOLUM TORQUATUS DIXIT QUID SENTIRET, SED ETIAM CUR.</LI>
        <LI>NEC ENIM, OMNES AVARITIAS SI AEQUE AVARITIAS ESSE DIXERIMUS, SEQUETUR UT ETIAM AEQUAS ESSE DICAMUS.</LI>
        <LI>CONFERAM TECUM, QUAM CUIQUE VERSO REM SUBICIAS;</LI>
        <LI>ALITER ENIM NOSMET IPSOS NOSSE NON POSSUMUS.</LI>
        <LI>ILLUM MALLEM LEVARES, QUO OPTIMUM ATQUE HUMANISSIMUM VIRUM, CN.</LI>
        <LI>VITAE AUTEM DEGENDAE RATIO MAXIME QUIDEM ILLIS PLACUIT QUIETA.</LI>
</OL>


<BLOCKQUOTE CITE='HTTP://LORIPSUM.NET'>
        QUOD NISI ITA EFFICITUR, QUAE THEOPHRASTUS DE FORTUNA, DE DOLORE, DE CRUCIATU CORPORIS DIXIT, CUM QUIBUS CONIUNGI VITAM BEATAM NULLO MODO POSSE PUTAVIT, VEREOR, NE VERA SINT.
</BLOCKQUOTE>


<OL>
        <LI>QUOD DICIT EPICURUS ETIAM DE VOLUPTATE, QUAE MINIME SINT VOLUPTATES, EAS OBSCURARI SAEPE ET OBRUI.</LI>
        <LI>AT VERO SI AD VITEM SENSUS ACCESSERIT, UT APPETITUM QUENDAM HABEAT ET PER SE IPSA MOVEATUR, QUID FACTURAM PUTAS?</LI>
        <LI>NULLUS EST IGITUR CUIUSQUAM DIES NATALIS.</LI>
        <LI>NON AUTEM HOC: IGITUR NE ILLUD QUIDEM.</LI>
        <LI>NOSTI, CREDO, ILLUD: NEMO PIUS EST, QUI PIETATEM-;</LI>
        <LI>CUM AUTEM NEGANT EA QUICQUAM AD BEATAM VITAM PERTINERE, RURSUS NATURAM RELINQUUNT.</LI>
</OL>


<H2>UT ENIM CONSUETUDO LOQUITUR, ID SOLUM DICITUR HONESTUM, QUOD EST POPULARI FAMA GLORIOSUM.</H2>

<P><CODE>INDE IGITUR, INQUIT, ORDIENDUM EST.</CODE> AT VERO ILLA PERFECTA ATQUE PLENA EORUM, QUI CUM DE HOMINIS SUMMO BONO QUAERERENT, NULLAM IN EO NEQUE ANIMI NEQUE CORPORIS PARTEM VACUAM TUTELA RELIQUERUNT. TENUIS LUCIUS VERGINIUS UNUSQUE DE MULTIS <I>[REDACTED]</I>AGESIMO ANNO POST LIBERTATEM RECEPTAM VIRGINEM FILIAM SUA MANU OCCIDIT POTIUS, QUAM EA AP. SIN ALIUD QUID VOLES, POSTEA. DUM ENIM IN UNA VIRTUTE SIC OMNIA ESSE VOLUERUNT, UT EAM RERUM SELECTIONE EXPOLIARENT NEC EI QUICQUAM, AUT UNDE ORIRETUR, DARENT, AUT UBI NITERETUR, VIRTUTEM IPSAM, QUAM AMPLEXABANTUR, SUSTULERUNT. QUAE ANIMI AFFECTIO SUUM CUIQUE TRIBUENS ATQUE HANC, QUAM DICO. QUID, SI REVIVISCANT PLATONIS ILLI ET DEINCEPS QUI EORUM AUDITORES FUERUNT, ET TECUM ITA LOQUANTUR? ETENIM NEC IUSTITIA NEC AMICITIA ESSE OMNINO POTERUNT, NISI IPSAE PER SE EXPETUNTUR. HOC AUTEM TEMPORE, ETSI MULTA IN OMNI PARTE ATHENARUM SUNT IN IPSIS LOCIS INDICIA SUMMORUM VIRORUM, TAMEN EGO ILLA MOVEOR EXHEDRA. EX QUO ILLUD EFFICITUR, QUI BENE CENENT OMNIS LIBENTER CENARE, QUI LIBENTER, NON CONTINUO BENE. DIXERIT HOC IDEM EPICURUS, SEMPER BEATUM ESSE SAPIENTEM-QUOD QUIDEM SOLET EBULLIRE NON NUMQUAM -, QUEM QUIDEM, CUM SUMMIS DOLORIBUS CONFICIATUR, AIT DICTURUM: QUAM SUAVE EST! QUAM NIHIL CURO!; APPELLET HAEC DESIDERIA NATURAE, CUPIDITATIS NOMEN SERVET ALIO, UT EAM, CUM DE AVARITIA, CUM DE INTEMPERANTIA, CUM DE MAXIMIS VITIIS LOQUETUR, TAMQUAM CAPITIS ACCUSET. SED ITA FALSA SUNT EA, QUAE CONSEQUUNTUR, UT ILLA, E QUIBUS HAEC NATA SUNT, VERA ESSE NON POSSINT. <I>TRIA GENERA BONORUM;</I> </P>

<P>QUA IN VITA TANTUM ABEST UT VOLUPTATES CONSECTENTUR, ETIAM CURAS, SOLLICITUDINES, VIGILIAS PERFERUNT OPTIMAQUE PARTE HOMINIS, QUAE IN NOBIS DIVINA DUCENDA EST, INGENII ET MENTIS ACIE FRUUNTUR NEC VOLUPTATEM REQUIRENTES NEC FUGIENTES LABOREM. QUA IGITUR RE AB DEO VINCITUR, SI AETERNITATE NON VINCITUR? QUOD NON SUBDUCTA UTILITATIS RATIONE EFFICI SOLET, SED IPSUM A SE ORITUR ET SUA SPONTE NASCITUR. <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>AT MULTIS MALIS AFFECTUS.</A> CUM AUTEM USUS PROGREDIENS FAMILIARITATEM EFFECERIT, TUM AMOREM EFFLORESCERE TANTUM, UT, ETIAMSI NULLA SIT UTILITAS EX AMICITIA, TAMEN IPSI AMICI PROPTER SE IPSOS AMENTUR. ILLA ENIM, QUAE SUNT A NOBIS BONA CORPORIS NUMERATA, COMPLENT EA QUIDEM BEATISSIMAM VITAM, SED ITA, UT SINE ILLIS POSSIT BEATA VITA EXISTERE. QUAE QUIDEM RES EFFICIT, NE NECESSE SIT ISDEM DE REBUS SEMPER QUASI DICTATA DECANTARE NEQUE A COMMENTARIOLIS SUIS DISCEDERE. MULTI ENIM ET MAGNI PHILOSOPHI HAEC ULTIMA BONORUM IUNCTA FECERUNT, UT ARISTOTELES VIRTUTIS USUM CUM VITAE PERFECTAE PROSPERITATE CONIUNXIT, CALLIPHO ADIUNXIT AD HONESTATEM VOLUPTATEM, DIODORUS AD EANDEM HONESTATEM ADDIDIT VACUITATEM DOLORIS. <B>TUM TORQUATUS: PRORSUS, INQUIT, ASSENTIOR;</B> <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>SINT ISTA GRAECORUM;</A> POSSUMUSNE ERGO IN VITA SUMMUM BONUM DICERE, CUM ID NE IN CENA QUIDEM POSSE VIDEAMUR? </P>

<P>QUAM OB REM TANDEM, INQUIT, NON SATISFACIT? TENUIT PERMAGNAM <I>[REDACTED]</I>TILIUS HEREDITATEM, UNDE, SI SECUTUS ESSET EORUM SENTENTIAM, QUI HONESTA ET RECTA EMOLUMENTIS OMNIBUS ET COMMODIS ANTEPONERENT, NUMMUM NULLUM ATTIGISSET. ITA FIT ILLA CONCLUSIO NON SOLUM VERA, SED ITA PERSPICUA, UT DIALECTICI NE RATIONEM QUIDEM REDDI PUTENT OPORTERE: SI ILLUD, HOC; HOC AUTEM LOCO TANTUM EXPLICEMUS HAEC HONESTA, QUAE DICO, PRAETERQUAM QUOD NOSMET IPSOS DILIGAMUS, PRAETEREA SUAPTE NATURA PER SE ESSE EXPETENDA. NAM LIBERO TEMPORE, CUM SOLUTA NOBIS EST ELIGENDI OPTIO, CUMQUE NIHIL IMPEDIT, QUO MINUS ID, QUOD MAXIME PLACEAT, FACERE POSSIMUS, OMNIS VOLUPTAS ASSUMENDA EST, OMNIS DOLOR REPELLENDUS. ITAQUE NON OB EA SOLUM INCOMMODA, QUAE EVENIUNT INPROBIS, FUGIENDAM INPROBITATEM PUTAMUS, SED MULTO ETIAM MAGIS, QUOD, CUIUS IN ANIMO VERSATUR, NUMQUAM SINIT EUM RESPIRARE, NUMQUAM ADQUIESCERE. </P>

<UL>
        <LI>NUNC OMNI VIRTUTI VITIUM CONTRARIO NOMINE OPPONITUR.</LI>
        <LI>QUID, CUM FICTAS FABULAS, E QUIBUS UTILITAS NULLA ELICI POTEST, CUM VOLUPTATE LEGIMUS?</LI>
</UL>


<P><CODE>NON EST IGITUR SUMMUM MALUM DOLOR.</CODE> <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>DE ILLIS, CUM VOLEMUS.</A> <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>SUMMUS DOLOR PLURES DIES MANERE NON POTEST?</A> QUAE QUI NON VIDENT, NIHIL UMQUAM MAGNUM AC COGNITIONE DIGNUM AMAVERUNT. UTI TUM DENIQUE IUDICETUR BEATUSNE FUERIT, CUM EXTREMUM VITAE DIEM MORTE CONFECERIT, QUOD ILLE UNUS E SEPTEM SAPIENTIBUS NON SAPIENTER CROESUM MONUIT; CUM ENIM SUMMUM BONUM IN VOLUPTATE PONAT, NEGAT INFINITO TEMPORE AETATIS VOLUPTATEM FIERI MAIOREM QUAM FINITO ATQUE MODICO. AT CUM TUIS CUM DISSERAS, MULTA SUNT AUDIENDA ETIAM DE OBSCENIS VOLUPTATIBUS, DE QUIBUS AB EPICURO SAEPISSIME DICITUR. QUI AUTEM VOLUPTATE VITAM EFFICI BEATAM PUTABIT, QUI SIBI IS CONVENIET, SI NEGABIT VOLUPTATEM CRESCERE LONGINQUITATE? QUARE, QUONIAM DE PRIMIS NATURAE COMMODIS SATIS DIETUM EST NUNC DE MAIORIBUS CONSEQUENTIBUSQUE VIDEAMUS. CUM ENIM SUPERIORES, E QUIBUS PLANISSIME POLEMO, SECUNDUM NATURAM VIVERE SUMMUM BONUM ESSE DIXISSENT, HIS VERBIS TRIA SIGNIFICARI STOICI DICUNT, UNUM EIUS MODI, VIVERE ADHIBENTEM SCIENTIAM EARUM RERUM, QUAE NATURA EVENIRENT. STOICOS ROGA. TU ENIM ISTA LENIUS, HIC STOICORUM MORE NOS VEXAT. CUM EFFICERE NON POSSIT UT CUIQUAM, QUI IPSE SIBI NOTUS SIT, HOC EST QUI SUAM NATURAM SENSUMQUE PERSPEXERIT, VACUITAS DOLORIS ET VOLUPTAS IDEM ESSE VIDEATUR. QUAEQUE DE VIRTUTIBUS DICTA SUNT, QUEM AD MODUM EAE SEMPER VOLUPTATIBUS INHAERERENT, EADEM DE AMICITIA DICENDA SUNT. AT ILLE NON PERTIMUIT SANEQUE FIDENTER: ISTIS QUIDEM IPSIS VERBIS, INQUIT; <B>AT COLUIT IPSE AMICITIAS.</B> <B>QUID ENIM?</B> AT TU EADEM ISTA DIC IN IUDICIO AUT, SI CORONAM TIMES, DIC IN SENATU. </P>

<P>QUEM ENIM DEDITUM VOLUPTATIBUS, QUEM CUPIDITATUM INCENDIIS INFLAMMATUM IN IIS POTIENDIS, QUAE ACERRIME CONCUPIVISSET, TANTA LAETITIA PERFUNDI ARBITRAMUR, QUANTA AUT SUPERIOREM AFRICANUM HANNIBALE VICTO AUT POSTERIOREM KARTHAGINE EVERSA? IUDICIA RERUM IN SENSIBUS PONIT, QUIBUS SI SEMEL ALIQUID FALSI PRO VERO PROBATUM SIT, SUBLATUM ESSE OMNE IUDICIUM VERI ET FALSI PUTAT. <MARK>QUAERIMUS ENIM FINEM BONORUM.</MARK> <CODE>NUNC HAEC PRIMUM FORTASSE AUDIENTIS SERVIRE DEBEMUS.</CODE> OMNIBUS ENIM ARTIBUS VOLUMUS ATTRIBUTAM ESSE EAM, QUAE COMMUNIS APPELLATUR PRUDENTIA, QUAM OMNES, QUI CUIQUE ARTIFICIO PRAESUNT, DEBENT HABERE. QUI SI EA, QUAE DICIT, ITA SENTIRET, UT VERBA SIGNIFICANT, QUID INTER EUM ET VEL PYRRHONEM VEL ARISTONEM INTERESSET? <MARK>QUAERIMUS ENIM FINEM BONORUM.</MARK> BONUM INCOLUMIS ACIES: MISERA CAECITAS. <B>SED AD ILLUM REDEO.</B> QUONIAMQUE NON DUBIUM EST QUIN IN IIS, QUAE MEDIA DICIMUS, SIT ALIUD SUMENDUM, ALIUD REICIENDUM, QUICQUID ITA FIT AUT DICITUR, OMNE OFFICIO CONTINETUR. </P>

<PRE>
ITAQUE UT MAIORES NOSTRI AB ARATRO ADDUXERUNT CINCINNATUM
ILLUM, UT DICTATOR ESSET, SIC VOS DE PAGIS OMNIBUS
COLLIGITIS BONOS ILLOS QUIDEM VIROS, SED CERTE NON
PERERUDITOS.

ET ADHUC QUIDEM ITA NOBIS PROGRESSO RATIO EST, UT EA
DUCERETUR OMNIS A PRIMA COMMENDATIONE NATURAE.
</PRE>


<BLOCKQUOTE CITE='HTTP://LORIPSUM.NET'>
        ILLA ENIM, QUAE PROSUNT AUT QUAE NOCENT, AUT BONA SUNT AUT MALA, QUAE SINT PARIA NECESSE EST.
</BLOCKQUOTE>


<H3>QUAE FERE OMNIA APPELLANTUR UNO INGENII NOMINE, EASQUE VIRTUTES QUI HABENT, INGENIOSI VOCANTUR.</H3>

<P>IPSE NEGAT, UT ANTE DIXI, LUXURIOSORUM VITAM REPREHENDENDAM, NISI PLANE FATUI SINT, ID EST NISI AUT CUPIANT AUT METUANT. SCIS ENIM ME QUODAM TEMPORE METAPONTUM VENISSE TECUM NEQUE AD HOSPITEM ANTE DEVERTISSE, QUAM PYTHAGORAE IPSUM ILLUM LOCUM, UBI VITAM EDIDERAT, SEDEMQUE VIDERIM. ESTO, FECERIT, SI ITA VIS, TORQUATUS PROPTER SUAS UTILITATESMALO ENIM DICERE QUAM VOLUPTATES, IN TANTO PRAESERTIM VIRO-, NUM ETIAM EIUS COLLEGA P. HONESTUM IGITUR ID INTELLEGIMUS, QUOD TALE EST, UT DETRACTA OMNI UTILITATE SINE ULLIS PRAEMIIS FRUCTIBUSVE PER SE IPSUM POSSIT IURE LAUDARI. ERGO IN IIS ADOLESCENTIBUS BONAM SPEM ESSE DICEMUS ET MAGNAM INDOLEM, QUOS SUIS COMMODIS INSERVITUROS ET QUICQUID IPSIS EXPEDIAT FACTUROS ARBITRABIMUR? <B>QUOD QUIDEM IAM FIT ETIAM IN ACADEMIA.</B> <B>FRATER ET T.</B> CONSTITUTO AUTEM ILLO, DE QUO ANTE DIXIMUS, QUOD HONESTUM ESSET, ID ESSE SOLUM BONUM, INTELLEGI NECESSE EST PLURIS ID, QUOD HONESTUM SIT, AESTIMANDUM ESSE QUAM ILLA MEDIA, QUAE EX EO COMPARENTUR. <CODE>COMPENSABATUR, INQUIT, CUM SUMMIS DOLORIBUS LAETITIA.</CODE> MAXIMAS VERO VIRTUTES IACERE OMNIS NECESSE EST VOLUPTATE DOMINANTE. NULLUM INVENIRI VERBUM POTEST QUOD MAGIS IDEM DECLARET LATINE, QUOD GRAECE, QUAM DECLARAT VOLUPTAS. <I>EADEMNE, QUAE RESTINCTA SITI?</I> </P>

<P>SI SAPIENS, NE TUM QUIDEM MISER, CUM AB OROETE, PRAETORE DAREI, IN CRUCEM ACTUS EST. QUA EX COGNITIONE FACILIOR FACTA EST INVESTIGATIO RERUM OCCULTISSIMARUM. SI SAPIENS, NE TUM QUIDEM MISER, CUM AB OROETE, PRAETORE DAREI, IN CRUCEM ACTUS EST. AN DUBIUM EST, QUIN VIRTUS ITA MAXIMAM PARTEM OPTINEAT IN REBUS HUMANIS, UT RELIQUAS OBRUAT? <CODE>QUID ERGO?</CODE> TUM ILLE: FINEM, INQUIT, INTERROGANDI, SI VIDETUR, QUOD QUIDEM EGO A PRINCIPIO ITA ME MALLE DIXERAM HOC IPSUM PROVIDENS, DIALECTICAS CAPTIONES. PRIMUM ENIM, SI VERA SUNT EA, QUORUM RECORDATIONE TE GAUDERE DICIS, HOC EST, SI VERA SUNT TUA SCRIPTA ET INVENTA, GAUDERE NON POTES. NAM SI +OMNINO NOS+ NEGLEGEMUS, IN ARISTONEA VITIA INCIDEMUS ET PECCATA OBLIVISCEMURQUE QUAE VIRTUTI IPSI PRINCIPIA DEDERIMUS; NATURALEM ENIM APPETITIONEM, QUAM VOCANT O)RMH)N, ITEMQUE OFFICIUM, IPSAM ETIAM VIRTUTEM TUENTEM VOLUNT ESSE EARUM RERUM, QUAE SECUNDUM NATURAM SUNT. ID QUAERIS, INQUAM, IN QUO, UTRUM RESPONDERO, VERSES TE HUC ATQUE ILLUC NECESSE EST. VIRTUTIS ENIM BEATAEQUE VITAE, QUAE DUO MAXIME EXPETENDA SUNT, SERIUS LUMEN APPARET, MULTO ETIAM SERIUS, UT PLANE QUALIA SINT INTELLEGANTUR. ID QUAERIS, INQUAM, IN QUO, UTRUM RESPONDERO, VERSES TE HUC ATQUE ILLUC NECESSE EST. QUI POTEST IGITUR HABITARE IN BEATA VITA SUMMI MALI METUS? SUPERIORES TRES ERANT, QUAE ESSE POSSENT, QUARUM EST UNA SOLA DEFENSA, EAQUE VEHEMENTER. IAM ILLE SORITES, QUO NIHIL PUTATIS ESSE VITIOSIUS: QUOD BONUM SIT, ID ESSE OPTABILE, QUOD OPTABILE, ID EXPETENDUM, QUOD EXPETENDUM, ID LAUDABILE, DEINDE RELIQUI GRADUS. NAM VOLUPTATIS CAUSA FACERE OMNIA, CUM, ETIAMSI NIHIL CONSEQUAMUR, TAMEN IPSUM ILLUD CONSILIUM ITA FACIENDI PER SE EXPETENDUM ET HONESTUM ET SOLUM BONUM SIT, NEMO DIXIT. </P>

<UL>
        <LI>HAEC QUO MODO CONVENIANT, NON SANE INTELLEGO.</LI>
        <LI>EXPRESSA VERO IN IIS AETATIBUS, QUAE IAM CONFIRMATAE SUNT.</LI>
        <LI>APPARET STATIM, QUAE SINT OFFICIA, QUAE ACTIONES.</LI>
        <LI>SIN KAKAN MALITIAM DIXISSES, AD ALIUD NOS UNUM CERTUM VITIUM CONSUETUDO LATINA TRADUCERET.</LI>
        <LI>IDCIRCO ENIM NON DESIDERARET, QUIA, QUOD DOLORE CARET, ID IN VOLUPTATE EST.</LI>
        <LI>DOLOR ERGO, ID EST SUMMUM MALUM, METUETUR SEMPER, ETIAMSI NON ADERIT;</LI>
</UL>


<P><CODE>UT PULSI RECURRANT?</CODE> <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>ITA PRORSUS, INQUAM;</A> <I>IN SCHOLA DESINIS.</I> NAM CETERIS IN REBUS SíVE PRAETERMISSUM SIVE IGNORATUM EST QUIPPIAM, NON PLUS INCOMMODI EST, QUAM QUANTI QUAEQUE EARUM RERUM EST, IN QUIBUS NEGLECTUM EST ALIQUíD. SIT VOLUPTAS NON MINOR IN NASTURCIO ILLO, QUO VESCI PERSAS ESSE SOLITOS SCRIBIT XENOPHON, QUAM IN SYRACUSANIS MENSIS, QUAE A PLATONE GRAVITER VITUPERANTUR; <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>SED HAEC OMITTAMUS;</A> <I>EGONE QUAERIS, INQUIT, QUID SENTIAM?</I> AN TU ME DE L. <A HREF='HTTP://LORIPSUM.NET/' TARGET='_BLANK'>UT PULSI RECURRANT?</A> NAM SUNT ET IN ANIMO PRAECIPUA QUAEDAM ET IN CORPORE, QUAE CUM LEVITER AGNOVIT, TUM DISCERNERE INCIPIT, UT EA, QUAE PRIMA DATA SUNT NATURA, APPETAT ASPERNETURQUE CONTRARIA. ESTO, FECERIT, SI ITA VIS, TORQUATUS PROPTER SUAS UTILITATESMALO ENIM DICERE QUAM VOLUPTATES, IN TANTO PRAESERTIM VIRO-, NUM ETIAM EIUS COLLEGA P. QUO POSITO ET OMNIUM ADSENSU ADPROBATO ILLUD ADSUMITUR, EUM, QUI MAGNO SIT ANIMO ATQUE FORTI, OMNIA, QUAE CADERE IN HOMINEM POSSINT, DESPICERE AC PRO NIHILO PUTARE. RELIQUI SIBI CONSTITERUNT, UT EXTREMA CUM INITIIS CONVENIRENT, UT ARISTIPPO VOLUPTAS, HIERONYMO DOLORIS VACUITAS, CARNEADI FRUI PRINCIPIIS NATURALIBUS ESSET EXTREMUM. </P>

<DL>
        <DT><DFN>IDEM ADHUC;</DFN></DT>
        <DD>ETENIM NEC IUSTITIA NEC AMICITIA ESSE OMNINO POTERUNT, NISI IPSAE PER SE EXPETUNTUR.</DD>
        <DT><DFN>AUDEO DICERE, INQUIT.</DFN></DT>
        <DD>ITA REDARGUITUR IPSE A SESE, CONVINCUNTURQUE SCRIPTA EIUS PROBITATE IPSIUS AC MORIBUS.</DD>
        <DT><DFN>NON IGITUR BENE.</DFN></DT>
        <DD>INDICANT PUERI, IN QUIBUS UT IN SPECULIS NATURA CERNITUR.</DD>
</DL>
*/
?>
